-- ===========================================================================
-- EcoSoch Project Repository - CONSOLIDATED PRODUCTION DATABASE CREATION
-- ===========================================================================
-- Run this ONCE in the production Supabase SQL editor to create the entire
-- schema (final column types, defaults, constraints) + the dropdowns table
-- seeded with its 138 built-in values. It mirrors the vetted staging schema.
--
-- After this, load the data (copy from staging via pg_dump, or run the
-- backfill against the prod backend). Tables are created empty here.
--
-- Idempotent: every statement uses IF NOT EXISTS. Re-running is safe, but note
-- that IF NOT EXISTS will NOT add a missing constraint to an already-existing
-- table - run on a fresh database.
-- Tables are created in dependency order (Clients before Projects for the FK).
-- ===========================================================================


-- ---------- Clients (parent of Projects) ----------
create table if not exists "Clients" (
  "Client_Id"            text primary key,
  "Client_Name"          text,
  "Client_Mobile"        text,
  "Client_Email"         text,
  "Client_Address"       text,
  "Client_Region"        text,
  "Client_Identity"      text,
  "Client_Status"        text,
  "Client_Type"          text,
  "Client_Notes"         text,
  "Client_GMap_Location" text,
  "synced_at"            timestamptz default now(),
  constraint clients_name_unique unique ("Client_Name")
);

-- ---------- Users ----------
create table if not exists "Users" (
  "Email"       text primary key,
  "User_Name"   text,
  "User_Role"   text,
  "Department"  text,
  "User_Status" text,
  "synced_at"   timestamptz default now()
);

-- ---------- Launcher ----------
create table if not exists "Launcher" (
  "App_Id"        text primary key,
  "App_Name"      text,
  "Icon"          text,
  "Sub_Header"    text,
  "Display_Order" text,
  "User_Role"     text,
  "synced_at"     timestamptz default now()
);

-- ---------- dropdowns (admin-managed dropdown options) ----------
create table if not exists "dropdowns" (
  "Option_Id"         text primary key,
  "Field_Key"         text,
  "Value"             text,
  "Active"            text,
  "Sort_Order"        numeric,
  "Created_By"        text,
  "Created_Date"      date,
  "Last_Updated_By"   text,
  "Last_Updated_Date" date,
  "synced_at"         timestamptz default now()
);
create unique index if not exists dropdowns_fieldkey_value_uidx on "dropdowns" ("Field_Key","Value");

-- ---------- Projects (FK -> Clients) ----------
create table if not exists "Projects" (
  "Project_ID"             text primary key,
  "Client_Name"            text,
  "Project_Name"           text,
  "Site_Area"              text,
  "Project_Size"           numeric,
  "Project_Type"           text,
  "AMC_Provided"           text,
  "AMC_Type"               text,
  "Project_Status"         text,
  "Prev_Project_Status"    text,
  "Site_Address"           text,
  "Project_Region"         text,
  "Project_Comments"       text,
  "Project_Description"    text,
  "Sales_Lead"             text,
  "Building_Type"          text,
  "Business_Model"         text,
  "Inverter_Brand"         text,
  "Inverter_Type"          text,
  "Module_Brand"           text,
  "Module_Wattage"         numeric,
  "Module_No"              numeric,
  "Roof_Material"          text,
  "Roof_Type"              text,
  "Project_Sector"         text,
  "System_Type"            text,
  "System_Category"        text,
  "Order_Value"            numeric,
  "Margin"                 numeric(6,2),
  "Proposal_Model"         text,
  "Client_Committment"     text,
  "Obstacle_Removal"       text,
  "Obstacle_Scope"         text,
  "Salesperson_Email"      text,
  "Payments_Done"          text,
  "Commissioned_Date"      date,
  "Warranty_Status"        text,
  "Warranty_Period"        numeric,
  "Warranty_Start_Date"    date,
  "Warranty_End_Date"      date,
  "GST_Number"             text,
  "DISCOM_Name"            text,
  "Billing_Name"           text,
  "Deal_ID"                text,
  "Subsidy"                text,
  "BESCOM"                 text,
  "Monitoring"             text,
  "Exp_Inst_Date"          date,
  "Exp_Commsn_Date"        date,
  "Quote_Sheet"            text,
  "Proposal"               text,
  "Files"                  text,
  "Bill_File"              text,
  "PO_File"                text,
  "Created_By"             text,
  "Created_Date"           date default ((now() at time zone 'Asia/Kolkata')::date),
  "Last_Updated_By"        text,
  "Last_Updated_Date"      date default ((now() at time zone 'Asia/Kolkata')::date),
  "GMap_Link"              text,
  "Quote_Sheet_Name"       text,
  "Proposal_Name"          text,
  "Files_Name"             text,
  "Bill_File_Name"         text,
  "PO_File_Name"           text,
  "synced_at"              timestamptz default now(),
  "Client_Id"              text,
  "Bill_Available"         text,
  "PO_Available"           text,
  "PO_Bill_Name_Same"      text,
  "Billing_Quotation_Same" text,
  "GST_Available"          text,
  "Quotation_Name"         text,
  "Referral"               text,
  "Referral_Amount"        numeric,
  "Referrer_Name"          text,
  "Retention"              text,
  "Retention_Amount"       numeric,
  "Retention_Period"       text,
  "Monitoring_Frequency"   text,
  "TSV_Required"           text,
  "Capacity_Finalised"     text,
  "Elevated_drawings"      text,
  "New_Order_Sent_At"      date,
  "New_Order_Sent_By"      text,
  "Internal_Id"            text,
  constraint projects_client_fk foreign key ("Client_Id")
    references "Clients" ("Client_Id") on update cascade on delete set null
);

-- ---------- AMC_Contracts ----------
create table if not exists "AMC_Contracts" (
  "AMC_Id"                  text primary key,
  "Project_ID"              text,
  "AMC_Type"                text,
  "AMC_Frequency"           numeric,
  "AMC_Period_in_Years"     numeric,
  "AMC_Start_Date"          date,
  "AMC_End_Date"            date,
  "AMC_Status"              text,
  "Payment_Amount"          numeric,
  "Payment_Status"          text,
  "Tasks_Count"             numeric,
  "Payments_Count"          numeric,
  "AMC_Contract_Files"      text,
  "Payment_Available"       text,
  "Percent_Increase"        numeric,
  "Payment_Frequency"       numeric,
  "Payment_Period_in_Years" numeric,
  "Payment_Start_Date"      date,
  "Payment_End_Date"        date,
  "AMC_Tasks_Done"          numeric,
  "Payments_Done"           numeric,
  "synced_at"               timestamptz default now()
);

-- ---------- AMC_Tasks_Schedule ----------
create table if not exists "AMC_Tasks_Schedule" (
  "AMC_Task_Id"     text primary key,
  "AMC_Id"          text,
  "AMC_Type"        text,
  "AMC_Due_Date"    date,
  "AMC_Description" text,
  "AMC_Resolution"  text,
  "AMC_Task_Status" text,
  "AMC_Task_Report" text,
  "Payment_Id"      text,
  "synced_at"       timestamptz default now()
);

-- ---------- AMC_Payment_Schedule ----------
create table if not exists "AMC_Payment_Schedule" (
  "Payment_Id"          text primary key,
  "AMC_Id"              text,
  "AMC_Type"            text,
  "Payment_Amount"      numeric,
  "Payment_Due_Date"    date,
  "Payment_Description" text,
  "Payment_Resolution"  text,
  "Payment_Status"      text,
  "Payment_Receipt"     text,
  "synced_at"           timestamptz default now()
);

-- ---------- Tickets ----------
create table if not exists "Tickets" (
  "Ticket_Id"                  text primary key,
  "Project_ID"                 text,
  "Ticket_Type"                text,
  "Ticket_Priority"            text,
  "Ticket_Description"         text,
  "Ticket_Status"              text,
  "Assigned_To"                text,
  "Progress_Update"            text,
  "Ticket_Resolution"          text,
  "Ticket_Start_Date"          date,
  "Ticket_Due_Date"            date,
  "Total_Charge"               numeric,
  "Ticket_Warranty_Status"     text,
  "Ticket_Warranty_Period"     numeric,
  "Ticket_Warranty_Start_Date" date,
  "Ticket_Warranty_End_Date"   date,
  "Material_Charge"            numeric,
  "Ticket_Payment_Status"      text,
  "Ticket_Payment_Receipt"     text,
  "Created_By"                 text,
  "Created_Date"               date,
  "Last_Updated_Date"          date,
  "Service_Charge_Applicable"  text,
  "Service_Charge"             numeric,
  "Material_Charge_Applicable" text,
  "Ticket_Expenses"            text,
  "Ticket_Files"               text,
  "Last_Updated_By"            text,
  "synced_at"                  timestamptz default now()
);

-- ---------- seed the dropdowns (138 built-in values) ----------
insert into "dropdowns" ("Option_Id","Field_Key","Value","Active","Created_By","Created_Date") values
  ('557473F2', 'Project_Type', 'EPC', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('B6FC0F37', 'Project_Type', 'I&C', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('33D1B60D', 'Project_Type', 'AMC', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('4D92F4D2', 'Project_Type', 'Consultancy', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('15672D7F', 'Project_Type', 'Retail', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('D6EAB5F7', 'Project_Type', 'Ad-hoc Maintenance', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('EE6C4E46', 'Project_Region', 'Bangalore', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8386122B', 'Project_Region', 'Rest of Karnataka', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E95BF5F3', 'Project_Region', 'Telangana', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('23FABFF3', 'Project_Region', 'TamilNadu', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('066DB0BE', 'Project_Region', 'Kerala', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('4728679D', 'Project_Region', 'Andhra Pradesh', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('653DE565', 'Project_Region', 'Maharashtra', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F0759B30', 'Project_Region', 'Rest of India', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('0BCB1C89', 'Client_Identity', 'Individual', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1B9F2F36', 'Client_Identity', 'Association', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8AD51405', 'Client_Identity', 'Company', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('5C59B4A2', 'Client_Identity', 'Institutional', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8F6DD226', 'Client_Identity', 'NGO', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('BF6F88E5', 'Sales_Lead', 'John', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('2F35BEC6', 'Sales_Lead', 'Joseph', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E6FC4324', 'Sales_Lead', 'Harsha', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('0F078ECB', 'Sales_Lead', 'Govindaraju JS', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('DAAE3ACF', 'Sales_Lead', 'Gautam', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('792F1D3A', 'Sales_Lead', 'Mahantayya', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('9320618A', 'Sales_Lead', 'Hariom', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('5EA1F622', 'Sales_Lead', 'Gaur', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1A5F8538', 'Sales_Lead', 'SolarCare', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('3C110287', 'Bill_Available', 'Yes', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('A33F2F93', 'Bill_Available', 'No. Have to ask customer to send the bill photo', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('6CEF7A44', 'Bill_Available', 'Not applicable', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('AAF9E0FA', 'Building_Type', 'Residence or Villa', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E7966D3F', 'Building_Type', 'Villa Community - Common Area', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('0586F2B0', 'Building_Type', 'Apartments', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('D212C1BB', 'Building_Type', 'Commercial', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FFF665F7', 'Building_Type', 'Industrial', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('BD9FB113', 'Building_Type', 'School', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('6676C4C4', 'Building_Type', 'Hospital', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('06315656', 'Building_Type', 'College', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('2664F348', 'Building_Type', 'Farm', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('69BC1CE3', 'Building_Type', 'Hotel', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F8BD7ECE', 'Building_Type', 'Resort', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('DB6747F9', 'Building_Type', 'Place of Worship', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FCE6CC0E', 'Building_Type', 'Other', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FD9715C0', 'Business_Model', 'CAPEX', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FE0325C3', 'Business_Model', 'CAPEX with Loan', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E20B39C1', 'Business_Model', 'OPEX', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E41E6A96', 'Inverter_Brand', 'Enphase', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('ECDFAF80', 'Inverter_Brand', 'SolarEdge', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('D3B26F20', 'Inverter_Brand', 'Deye', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('D5ABE8D1', 'Inverter_Brand', 'Feston', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('6416FA64', 'Inverter_Brand', 'Studer', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('2693DA94', 'Inverter_Brand', 'Luminous', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('04211C73', 'Inverter_Brand', 'Sukam', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F6BB6BE1', 'Inverter_Brand', 'Unipar', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('5ECD7638', 'Inverter_Brand', 'ABB', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('61D1603A', 'Inverter_Brand', 'Fronius', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('355681D2', 'Inverter_Brand', 'Sungrow', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('EA0D5624', 'Inverter_Brand', 'Havells', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FD6E693D', 'Inverter_Brand', 'MicroTek', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('64417BDD', 'Inverter_Brand', 'MRO-TEK', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('72AB9429', 'Inverter_Brand', 'Power-One', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F9ABDFFF', 'Inverter_Brand', 'GoodWe', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FBAD580E', 'Inverter_Brand', 'Grundfos', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('7EAEAF2F', 'Inverter_Brand', 'Shakti', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8940CCEC', 'Inverter_Type', 'Microinverter (IQ Series)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8F41DD82', 'Inverter_Type', 'String', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('42D0A8DC', 'Inverter_Type', 'Optimizer', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('AE68BEEB', 'Inverter_Type', 'Hybrid', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8B542642', 'Inverter_Type', 'Power Conditioning Unit (PCU)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('84A29C88', 'Inverter_Type', 'Variable Frequency Drive (VFD)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('9526A4EF', 'Inverter_Type', 'Off Grid', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('4A4CC044', 'Inverter_Type', 'UPS', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F7FC4A1B', 'Proposal_Model', 'Essential', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('948908B1', 'Proposal_Model', 'Premium', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('465C9029', 'Proposal_Model', 'NA (only for C&I projects)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('32818783', 'Module_Brand', 'Waaree', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('683F5175', 'Module_Brand', 'Adani', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('ABDB19A0', 'Module_Brand', 'Premier', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E5B62008', 'Module_Brand', 'Vikram Solar', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('0492D1DC', 'Module_Brand', 'Novasys', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8F65AB88', 'Module_Brand', 'Sunpower', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('67358B56', 'Module_Brand', 'NA', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1FF8AA97', 'Module_Brand', 'Axitec', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('59EC5EAA', 'Module_Brand', 'Trina', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('947DA824', 'Roof_Material', 'RCC', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('B46B0855', 'Roof_Material', 'Corrugated Sheet', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('5E9E6C79', 'Roof_Material', 'GI', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('2F21F065', 'Roof_Material', 'MS Rafter', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('B131225E', 'Roof_Type', 'Flat', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1895957B', 'Roof_Type', 'Sloped', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('89EA5275', 'Roof_Type', 'Elevated (HDGI) - Penetrative', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1F3DCBDE', 'Roof_Type', 'SolrFit - Non-penetrative', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('B6D41D81', 'Roof_Type', 'Elevated (MS)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('6310CFF9', 'Roof_Type', 'Tiled', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F404E488', 'Roof_Type', 'Special Structures (talk to Salesperson for details)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('00AA1A23', 'Roof_Type', 'BIPV', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('298EC838', 'Project_Sector', 'Residential', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('52FED2BA', 'Project_Sector', 'Commercial', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('6BEAF686', 'Project_Sector', 'Industrial', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('44022266', 'Project_Sector', 'Institutional', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('94595AB3', 'Project_Sector', 'Government', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('CBBBF800', 'Project_Sector', 'Agricultural', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('C22FF948', 'System_Type', 'Rooftop Solar', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('A8397769', 'System_Type', 'Solar DC Pump', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E5158322', 'System_Type', 'Solar AC Pump', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('0C7EC482', 'System_Type', 'EV Charging', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('963B38F4', 'System_Category', 'Grid-Tied', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('D506554D', 'System_Category', 'Off Grid', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('65D65154', 'System_Category', 'Hybrid', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('A35B7B69', 'System_Category', 'Grid-Supported', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('139A2E95', 'Monitoring_Frequency', 'Daily', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('247A8FD7', 'Monitoring_Frequency', 'Weekly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('12277295', 'Monitoring_Frequency', 'Fortnightly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('7F4ED7AF', 'Monitoring_Frequency', 'Monthly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('CE7393E7', 'Monitoring_Frequency', 'Quarterly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('71AD8AE5', 'Monitoring_Frequency', 'Half-Yearly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('C8F449E8', 'Monitoring_Frequency', 'Yearly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('C559856E', 'Ticket_Type', 'Breakdown', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('12A195E5', 'Ticket_Type', 'Generation Drop', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1E55D5B2', 'Ticket_Type', 'Inverter Fault', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('12947AD0', 'Ticket_Type', 'Module Damage', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('D3E9A076', 'Ticket_Type', 'Wiring / Electrical', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8096F81F', 'Ticket_Type', 'Structure', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FCA4E622', 'Ticket_Type', 'Monitoring', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('0EBB0F4F', 'Ticket_Type', 'Cleaning Request', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('26EB2FDE', 'Ticket_Type', 'Inspection Request', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('DB11B183', 'Ticket_Type', 'Other', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('99BA5150', 'Ticket_Priority', 'Low', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('75AF5E89', 'Ticket_Priority', 'Medium', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('C04167A7', 'Ticket_Priority', 'High', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('2F0F336F', 'Ticket_Priority', 'Critical', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('293763E3', 'Ticket_Status', 'Open', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('6F52979E', 'Ticket_Status', 'In Progress', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('6C7C643F', 'Ticket_Status', 'On Hold', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('77688918', 'Ticket_Status', 'Resolved', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('A88210D0', 'Ticket_Status', 'Closed', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('03D97C03', 'Ticket_Status', 'Cancelled', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date)
on conflict ("Field_Key","Value") do nothing;

-- ---------- verify ----------
select table_name,
       (select count(*) from information_schema.columns c where c.table_name = t.table_name) as cols
from information_schema.tables t
where t.table_schema = 'public'
order by table_name;

select "Field_Key", count(*) as options from "dropdowns" group by "Field_Key" order by "Field_Key";
