-- ===========================================================================
-- EcoSoch Project Repository — migrate dropdown options into Supabase.
-- Creates table "dropdowns" (mirrors the Dropdown_Options sheet tab) and seeds
-- it with the 138 built-in option values across 20 field keys. The Sheet's
-- Dropdown_Options tab is empty, so these built-ins ARE the canonical source
-- (the same set the Apps Script one-time import would insert).
-- Run on STAGING after deploying the matching backend code. Idempotent create;
-- the seed INSERT is guarded so re-running won't duplicate (Field_Key, Value).
-- ===========================================================================

create table if not exists "dropdowns" (
  "Option_Id"         text primary key,
  "Field_Key"         text,
  "Value"             text,
  "Active"            text,
  "Created_By"        text,
  "Created_Date"      date,
  "Last_Updated_By"   text,
  "Last_Updated_Date" date,
  synced_at           timestamptz default now()
);

-- de-dupe guard
create unique index if not exists dropdowns_fieldkey_value_uidx
  on "dropdowns" ("Field_Key", "Value");

insert into "dropdowns" ("Option_Id","Field_Key","Value","Active","Created_By","Created_Date") values
  ('164663A9', 'Project_Type', 'EPC', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('242DAA47', 'Project_Type', 'I&C', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('0D85F743', 'Project_Type', 'AMC', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('11D87891', 'Project_Type', 'Consultancy', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E6051F5A', 'Project_Type', 'Retail', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('BCBB920C', 'Project_Type', 'Ad-hoc Maintenance', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('38F77F1A', 'Project_Region', 'Bangalore', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('9D82A74A', 'Project_Region', 'Rest of Karnataka', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('764EA7CD', 'Project_Region', 'Telangana', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('6F0BE517', 'Project_Region', 'TamilNadu', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8F5BBDEF', 'Project_Region', 'Kerala', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('A4C9A828', 'Project_Region', 'Andhra Pradesh', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('18CCF40F', 'Project_Region', 'Maharashtra', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('DAE9E52A', 'Project_Region', 'Rest of India', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('4317C00B', 'Client_Identity', 'Individual', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('23D3D043', 'Client_Identity', 'Association', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('384878A5', 'Client_Identity', 'Company', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FE9377D9', 'Client_Identity', 'Institutional', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F4410CDA', 'Client_Identity', 'NGO', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('3E89A05D', 'Sales_Lead', 'John', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('069F983A', 'Sales_Lead', 'Joseph', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('9DDCAC41', 'Sales_Lead', 'Harsha', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('5E344043', 'Sales_Lead', 'Govindaraju JS', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('28B88F25', 'Sales_Lead', 'Gautam', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('2CC6A198', 'Sales_Lead', 'Mahantayya', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('63AF6935', 'Sales_Lead', 'Hariom', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('030E870D', 'Sales_Lead', 'Gaur', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('C8E4589D', 'Sales_Lead', 'SolarCare', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F9F70BCD', 'Bill_Available', 'Yes', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('670B48DA', 'Bill_Available', 'No. Have to ask customer to send the bill photo', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FA78BA65', 'Bill_Available', 'Not applicable', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('290EEE0B', 'Building_Type', 'Residence or Villa', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('C23BAADF', 'Building_Type', 'Villa Community - Common Area', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('687FDB50', 'Building_Type', 'Apartments', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('A5AA42D3', 'Building_Type', 'Commercial', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('A1EBB0DC', 'Building_Type', 'Industrial', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F6C5729E', 'Building_Type', 'School', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('68E82BBD', 'Building_Type', 'Hospital', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('6810F9EC', 'Building_Type', 'College', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('826ED461', 'Building_Type', 'Farm', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('2EB8D163', 'Building_Type', 'Hotel', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('3A83BA80', 'Building_Type', 'Resort', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('5440671A', 'Building_Type', 'Place of Worship', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8FD07596', 'Building_Type', 'Other', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('C7C18B70', 'Business_Model', 'CAPEX', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('4AEB158E', 'Business_Model', 'CAPEX with Loan', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('D9ECAA4B', 'Business_Model', 'OPEX', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('7844CBAC', 'Inverter_Brand', 'Enphase', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('5B59419A', 'Inverter_Brand', 'SolarEdge', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('3D0170AC', 'Inverter_Brand', 'Deye', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('C01F31EF', 'Inverter_Brand', 'Feston', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1C8FD378', 'Inverter_Brand', 'Studer', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('085630C5', 'Inverter_Brand', 'Luminous', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('B27AB362', 'Inverter_Brand', 'Sukam', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('CCFBBB82', 'Inverter_Brand', 'Unipar', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('43B44636', 'Inverter_Brand', 'ABB', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F646E188', 'Inverter_Brand', 'Fronius', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('EE29EAFE', 'Inverter_Brand', 'Sungrow', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1A50D24D', 'Inverter_Brand', 'Havells', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('65B7E8E8', 'Inverter_Brand', 'MicroTek', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('ED9049A4', 'Inverter_Brand', 'MRO-TEK', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F4F5DB3E', 'Inverter_Brand', 'Power-One', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F40B5864', 'Inverter_Brand', 'GoodWe', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1E6BCE21', 'Inverter_Brand', 'Grundfos', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FD9E31B9', 'Inverter_Brand', 'Shakti', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('40869124', 'Inverter_Type', 'Microinverter (IQ Series)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('44404C01', 'Inverter_Type', 'String', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('C4024942', 'Inverter_Type', 'Optimizer', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('9D533A2B', 'Inverter_Type', 'Hybrid', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1450816B', 'Inverter_Type', 'Power Conditioning Unit (PCU)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('AE69E48B', 'Inverter_Type', 'Variable Frequency Drive (VFD)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('20CF367B', 'Inverter_Type', 'Off Grid', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('7AC0A40C', 'Inverter_Type', 'UPS', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('5B9A2872', 'Proposal_Model', 'Essential', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('5BBA36CB', 'Proposal_Model', 'Premium', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F6D29F02', 'Proposal_Model', 'NA (only for C&I projects)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('DEECD50F', 'Module_Brand', 'Waaree', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('0C14B5B4', 'Module_Brand', 'Adani', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('938A0037', 'Module_Brand', 'Premier', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('B932ECBD', 'Module_Brand', 'Vikram Solar', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('4CC33820', 'Module_Brand', 'Novasys', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('CE9CC9C6', 'Module_Brand', 'Sunpower', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('2C58009E', 'Module_Brand', 'NA', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E4DFC07E', 'Module_Brand', 'Axitec', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('ABDCD557', 'Module_Brand', 'Trina', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('4389DDEA', 'Roof_Material', 'RCC', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('3DC7B988', 'Roof_Material', 'Corrugated Sheet', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('454709B0', 'Roof_Material', 'GI', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('2492F63A', 'Roof_Material', 'MS Rafter', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('A237971B', 'Roof_Type', 'Flat', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('529AFBF2', 'Roof_Type', 'Sloped', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('70F74321', 'Roof_Type', 'Elevated (HDGI) - Penetrative', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('90A72657', 'Roof_Type', 'SolrFit - Non-penetrative', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('336F2A75', 'Roof_Type', 'Elevated (MS)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('DAAAE862', 'Roof_Type', 'Tiled', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('1FFA9DC0', 'Roof_Type', 'Special Structures (talk to Salesperson for details)', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('02508FCB', 'Roof_Type', 'BIPV', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E6FEBBD5', 'Project_Sector', 'Residential', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('233EA63F', 'Project_Sector', 'Commercial', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('0998BA3A', 'Project_Sector', 'Industrial', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('5C9DD6A2', 'Project_Sector', 'Institutional', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('67B417C4', 'Project_Sector', 'Government', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('E0881A45', 'Project_Sector', 'Agricultural', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('3680EF8C', 'System_Type', 'Rooftop Solar', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('3E0DDFCE', 'System_Type', 'Solar DC Pump', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('D15317F4', 'System_Type', 'Solar AC Pump', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('CE02D61E', 'System_Type', 'EV Charging', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('8BF4BE8F', 'System_Category', 'Grid-Tied', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('C21B73AC', 'System_Category', 'Off Grid', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('CDCC96B3', 'System_Category', 'Hybrid', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('48A2CA19', 'System_Category', 'Grid-Supported', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('DD6F69E1', 'Monitoring_Frequency', 'Daily', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('45683E01', 'Monitoring_Frequency', 'Weekly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('78BE3639', 'Monitoring_Frequency', 'Fortnightly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('DB329BD9', 'Monitoring_Frequency', 'Monthly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('4FB84B7F', 'Monitoring_Frequency', 'Quarterly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('AA5A69A3', 'Monitoring_Frequency', 'Half-Yearly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('6B146F0D', 'Monitoring_Frequency', 'Yearly', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('07DAD528', 'Ticket_Type', 'Breakdown', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('02495891', 'Ticket_Type', 'Generation Drop', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('52593901', 'Ticket_Type', 'Inverter Fault', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('76CD7676', 'Ticket_Type', 'Module Damage', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F3ADDBC0', 'Ticket_Type', 'Wiring / Electrical', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F3F6C8EE', 'Ticket_Type', 'Structure', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('4B4255F1', 'Ticket_Type', 'Monitoring', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('B4D3CDE5', 'Ticket_Type', 'Cleaning Request', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F540DE91', 'Ticket_Type', 'Inspection Request', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('A326E42E', 'Ticket_Type', 'Other', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('520F8E9C', 'Ticket_Priority', 'Low', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('92D93F85', 'Ticket_Priority', 'Medium', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('0B3AA371', 'Ticket_Priority', 'High', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('ADFEE8E3', 'Ticket_Priority', 'Critical', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('03797B8C', 'Ticket_Status', 'Open', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('F6837810', 'Ticket_Status', 'In Progress', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('A64A99BA', 'Ticket_Status', 'On Hold', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('73E98CCD', 'Ticket_Status', 'Resolved', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('EE326800', 'Ticket_Status', 'Closed', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date),
  ('FB921C93', 'Ticket_Status', 'Cancelled', 'true', 'built-in', (now() at time zone 'Asia/Kolkata')::date)
on conflict ("Field_Key","Value") do nothing;

select "Field_Key", count(*) from "dropdowns" group by "Field_Key" order by "Field_Key";
